// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKZ6RBAtGrvQCPxPUYOhEHRhGESF1p8sU',
    appId: '1:960504015815:web:92d95c3d873cf42dbac7e2',
    messagingSenderId: '960504015815',
    projectId: 'pop-collect',
    authDomain: 'pop-collect.firebaseapp.com',
    storageBucket: 'pop-collect.appspot.com',
    measurementId: 'G-R151WHNV9V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4613Zw71fZUNcUI9d8ePS4VerIEyJ3Yg',
    appId: '1:960504015815:android:45b34936d580c9f1bac7e2',
    messagingSenderId: '960504015815',
    projectId: 'pop-collect',
    storageBucket: 'pop-collect.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAINiy5ayiUOObrhu2KVAC5iY3gQzKosI0',
    appId: '1:960504015815:ios:916ab50f82556eacbac7e2',
    messagingSenderId: '960504015815',
    projectId: 'pop-collect',
    storageBucket: 'pop-collect.appspot.com',
    iosBundleId: 'com.example.popCollect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAINiy5ayiUOObrhu2KVAC5iY3gQzKosI0',
    appId: '1:960504015815:ios:916ab50f82556eacbac7e2',
    messagingSenderId: '960504015815',
    projectId: 'pop-collect',
    storageBucket: 'pop-collect.appspot.com',
    iosBundleId: 'com.example.popCollect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKZ6RBAtGrvQCPxPUYOhEHRhGESF1p8sU',
    appId: '1:960504015815:web:787a2127ce5725efbac7e2',
    messagingSenderId: '960504015815',
    projectId: 'pop-collect',
    authDomain: 'pop-collect.firebaseapp.com',
    storageBucket: 'pop-collect.appspot.com',
    measurementId: 'G-343X83WH9W',
  );
}
